// Generated by template-wizard/03_process_templates.py
// Do not edit manually

import type { TemplateConfig } from '../types/templateConfig'

export interface TemplateMeta {
  id: string
  name: string
  description: string
  category: string
  member: boolean
  defaultPreset: Partial<TemplateConfig>
}

export interface TemplatesConfig {
  version: number
  templates: TemplateMeta[]
}

const config: TemplatesConfig = {
  version: 1,
  templates: [
  {
    "id": "default",
    "name": "默认模板",
    "description": "默认 Word 模板，什么样式都没有。",
    "category": "free",
    "member": false,
    "defaultPreset": {
      "languageStyle": "zh-academic",
      "sectionNumbering": "none",
      "crossReference": "basic",
      "equationNumbering": "manual"
    }
  },
  {
    "id": "plain",
    "name": "经典模板",
    "description": "经典 Word 模板，带有基本样式。",
    "category": "free",
    "member": false,
    "defaultPreset": {
      "languageStyle": "zh-academic",
      "sectionNumbering": "none",
      "crossReference": "basic",
      "equationNumbering": "manual"
    }
  },
  {
    "id": "plain-member",
    "name": "经典模板",
    "description": "经典 Word 模板，带有基本样式。",
    "category": "member",
    "member": true,
    "defaultPreset": {
      "languageStyle": "zh-academic",
      "sectionNumbering": "none",
      "crossReference": "basic",
      "equationNumbering": "manual"
    }
  }
]
}

export default config
